# Generated by Django 3.2.9 on 2021-11-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0002_element_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='atomicmass',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='element',
            name='number',
            field=models.TextField(default='', max_length=20),
        ),
    ]
