# Generated by Django 3.2.9 on 2021-11-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0004_auto_20211110_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='atomicmass',
            field=models.TextField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='electronegativity',
            field=models.TextField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='metal',
            field=models.TextField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='non_metal',
            field=models.TextField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='number',
            field=models.TextField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='radioactivity',
            field=models.TextField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='symbol',
            field=models.TextField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='valance_electrons',
            field=models.TextField(default='', max_length=5),
        ),
    ]
