# Generated by Django 3.2.9 on 2021-11-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0005_auto_20211110_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='atomicmass',
            field=models.DecimalField(decimal_places=5, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='electronegativity',
            field=models.DecimalField(decimal_places=5, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='radioactivity',
            field=models.DecimalField(decimal_places=5, default='', max_digits=5),
        ),
        migrations.AlterField(
            model_name='element',
            name='valance_electrons',
            field=models.DecimalField(decimal_places=5, default='', max_digits=5),
        ),
    ]
